; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 
	nanoatmega328
src_dir = .
include_dir = .
description = Testversion des EX-IOExpanders für virtuelle digitale IO 

[env]
build_flags = 
	-Wall

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
board_build.f_cpu = 16000000L
build_flags = 
    -DF_CPU=16000000L
    -Wall
    -O2
monitor_speed = 115200